# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

#
# Create a branch
#

name: 'Create a branch'
description: "Creates a branch based on an issue ticket's title"
author: 'jonah jackson'

# Define your inputs here.
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  # issue_number:
  #   description: 'The number of the issue'
  #   required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true

# Define your outputs here.
outputs:
  success:
    description: 'branch was successfully created'

runs:
  using: node20
  main: dist/index.js
#
# Label an issue
#

# name: 'label an issue'
# description:
#   'Labels an issue as test
# author: 'jonah jackson'

# # Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

#   owner:
#     description: 'The owner of the repository'
#     required: true
#   repo:
#     description: 'The name of the repository'
#     required: true
#   issue_number:
#     description: 'The number of the issue'
#     required: true

#   project:
#     default: 'https://github.com/users/JonahJackson1/projects/1'
#     description: 'The url of the associated project'
#     required: true
#   column_name:
#     default: 'Ready'
#     description: 'The column name to move the issue to'
#     required: true

#   token:
#     description: 'The token to use to access the GitHub API'
#     required: true

# # Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

# runs:
#   using: node20
#   main: dist/index.js

#
# Move an issue in a project
# --- might not be possible in this format, will probably need to use a webhook
#

# name: 'label an issue'
# description:
#   'Labels an issue as test
# author: 'jonah jackson'

# # Define your inputs here.
# inputs:

#   owner:
#     description: 'The owner of the repository'
#     required: true
#   repo:
#     description: 'The name of the repository'
#     required: true
#   issue_number:
#     description: 'The number of the issue'
#     required: true

#   project:
#     default: 'https://github.com/users/JonahJackson1/projects/1'
#     description: 'The url of the associated project'
#     required: true
#   column_name:
#     default: 'Ready'
#     description: 'The column name to move the issue to'
#     required: true

#   token:
#     description: 'The token to use to access the GitHub API'
#     required: true

# # Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

# runs:
#   using: node20
#   main: dist/index.js
