# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: 'label issue'
description: 'labels an issue as test'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  issue_number:
    description: 'The number of the issue'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: node20
  main: dist/index.js

