# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

#
# Create a branch
#

name: 'Initialize a new issue ticket'
description: 'Creates and adds the basic requirements for an issue ticket'
author: 'jonah jackson'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  issue_number:
    description: 'The number of the issue'
    required: true
  issue_title:
    description: 'The title of the issue'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'
  branch:
    description: 'branch was successfully created'

runs:
  using: node20
  main: dist/index.js
