# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'initialize issue'
description:
  'Labels an issue as test and moves it to the "Ready" column in a project'
author: 'jonah jackson'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  issue_number:
    description: 'The number of the issue'
    required: true

  project:
    default: 'https://github.com/users/JonahJackson1/projects/1'
    description: 'The url of the associated project'
    required: true
  column_name:
    default: 'Ready'
    description: 'The column name to move the issue to'
    required: true

  token:
    description: 'The token to use to access the GitHub API'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
