name: Label and move new issues

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          curl -sSL \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"labels": ["new"]}' \
            "https://api.github.com/repos/JonahJackson1/testing-project-automation/issues/${{ github.event.issue.number }}/labels"
