name: Label and move new issues

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          curl -sSL \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"labels": ["test"]}'  \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels"

      # Conceptual step: Move issue to "Ready" column on project board
      # This requires the column ID of the "Ready" column and additional API calls.
      - name: Move issue to "Ready" column
        run: |
          issue_id=$(curl -sSL \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
            | jq .id)

          curl -sSL \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content_id\": $issue_id, \"content_type\": \"Issue\"}" \
            "https://api.github.com/projects/1/columns/4b2fdd91/cards"
