name: Label and move new issues

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          curl -sSL \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"labels": ["test"]}'  \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels"
